In [20]:
import numpy as np
from sklearn.linear_model import SGDClassifier

In [2]:
x = 2 * np.random.rand(100,1)
x

array([[0.07965035],
       [1.63437075],
       [1.60822076],
       [0.21816348],
       [1.96130704],
       [1.83935234],
       [1.06731193],
       [1.60918065],
       [1.50926712],
       [1.89672491],
       [1.23648508],
       [0.68448975],
       [0.95745039],
       [1.66563643],
       [0.33101724],
       [0.61157874],
       [0.0166755 ],
       [0.63583014],
       [1.33875655],
       [0.21034172],
       [0.76937692],
       [0.11596346],
       [1.30650082],
       [1.91061516],
       [1.81509799],
       [1.04680059],
       [0.61495191],
       [1.06426065],
       [0.03104153],
       [0.96427519],
       [1.68413677],
       [1.03696359],
       [1.28270236],
       [1.15378793],
       [1.51662185],
       [1.18999302],
       [1.2293329 ],
       [1.1713994 ],
       [1.77340761],
       [0.33014127],
       [0.86599744],
       [0.83604738],
       [0.53701022],
       [0.22647873],
       [1.3997355 ],
       [0.55953564],
       [1.12205447],
       [0.955

In [3]:
y = 3*x + 2 #in the form of y = mx+c (linear data) 
y

array([[2.23895105],
       [6.90311226],
       [6.82466227],
       [2.65449044],
       [7.88392112],
       [7.51805703],
       [5.20193578],
       [6.82754194],
       [6.52780137],
       [7.69017472],
       [5.70945524],
       [4.05346924],
       [4.87235116],
       [6.9969093 ],
       [2.99305171],
       [3.83473622],
       [2.05002651],
       [3.90749041],
       [6.01626965],
       [2.63102516],
       [4.30813077],
       [2.34789037],
       [5.91950245],
       [7.73184548],
       [7.44529397],
       [5.14040177],
       [3.84485572],
       [5.19278196],
       [2.09312459],
       [4.89282558],
       [7.05241032],
       [5.11089077],
       [5.84810707],
       [5.4613638 ],
       [6.54986555],
       [5.56997907],
       [5.6879987 ],
       [5.51419821],
       [7.32022282],
       [2.9904238 ],
       [4.59799231],
       [4.50814215],
       [3.61103066],
       [2.6794362 ],
       [6.19920649],
       [3.67860691],
       [5.3661634 ],
       [4.865

In [5]:
ones = np.ones((100,1))
x_b = np.c_[ones,x]
x_b

array([[1.        , 0.07965035],
       [1.        , 1.63437075],
       [1.        , 1.60822076],
       [1.        , 0.21816348],
       [1.        , 1.96130704],
       [1.        , 1.83935234],
       [1.        , 1.06731193],
       [1.        , 1.60918065],
       [1.        , 1.50926712],
       [1.        , 1.89672491],
       [1.        , 1.23648508],
       [1.        , 0.68448975],
       [1.        , 0.95745039],
       [1.        , 1.66563643],
       [1.        , 0.33101724],
       [1.        , 0.61157874],
       [1.        , 0.0166755 ],
       [1.        , 0.63583014],
       [1.        , 1.33875655],
       [1.        , 0.21034172],
       [1.        , 0.76937692],
       [1.        , 0.11596346],
       [1.        , 1.30650082],
       [1.        , 1.91061516],
       [1.        , 1.81509799],
       [1.        , 1.04680059],
       [1.        , 0.61495191],
       [1.        , 1.06426065],
       [1.        , 0.03104153],
       [1.        , 0.96427519],
       [1.

In [7]:
eta = 0.01
steps = 1000
m = 100
theta = np.random.rand(2,1)

In [15]:
for each_steps in range(steps):
    gradients = (2/100) * x_b.T.dot(x_b.dot(theta)-y) #formula = 2/m(x.t(x(theta)-y)
    theta = theta - eta * gradients

In [16]:
theta

array([[2.00013229],
       [2.9998878 ]])

In [28]:
sgd_reg = SGDRegressor(max_iter=100, tol = 0.03, eta0 = 0.01, random_state = 123)
sgd_reg.fit(x, y.ravel())

SGDRegressor(max_iter=100, random_state=123, tol=0.03)